const API = 'http' + '://localhost:4000/graphql';
const store = { students: [], courses: [], instructors: [], enrollments: [], page: 'dashboard', sort: {}, filters: {} };
const rolePages = { admin: { dashboard:['D','Dashboard'], students:['S','Students'], courses:['C','Courses'], instructors:['I','Instructors'], enrollments:['E','Enrollments'], settings:['O','Settings'] }, lecturer: { dashboard:['D','Dashboard'], students:['S','Students'], courses:['C','Courses'], grades:['G','Grades'] }, student: { dashboard:['D','Home'], profile:['P','My Profile'], mycourses:['C','My Courses'], grades:['G','My Grades'] } };
const roleLabels = { admin:['AM','Alex Morgan','University Administrator'], lecturer:['LK','Dr. Lee Kim','Lecturer'], student:['AJ','Alex Johnson','Computer Science Student'] };
const demoStudentEmail = 'student@campusconnect.edu';
store.grades = [];
rolePages.admin.grades = ['G','Grades'];

async function fetchGrades(){store.grades=(await request(`query{grades{id grade student{id name email} course{id title credits instructor{name}}}}`)).grades;}
async function assignGrade(input){return request(`mutation($input:AssignGradeInput!){assignGrade(input:$input){id}}`,{input});}
async function updateGrade(id,input){return request(`mutation($id:ID!,$input:UpdateGradeInput!){updateGrade(id:$id,input:$input){id}}`,{id,input});}
async function deleteGrade(id){return request(`mutation($id:ID!){deleteGrade(id:$id){id}}`,{id});}
const renderAdmin = render;

document.addEventListener('DOMContentLoaded', () => {
  document.getElementById('role-switch').onchange = (event) => applyRole(event.target.value);
  applyRole(localStorage.getItem('cc-role') || 'admin');
});

function applyRole(role) {
  store.role = role;
  store.page = 'dashboard';
  localStorage.setItem('cc-role', role);
  const [initials, name, title] = roleLabels[role];
  document.getElementById('profile-initials').textContent = initials;
  document.getElementById('profile-name').textContent = name;
  document.getElementById('profile-role-title').textContent = title;
  document.getElementById('role-switch').value = role;
  document.getElementById('profile-settings').style.display = role === 'admin' ? 'block' : 'none';
  // Keep the demo role switch available in every view; role permissions still
  // control the navigation and actions rendered for the selected role.
  document.querySelector('.role-picker').style.display = 'grid';
  const nav = document.getElementById('navigation');
  nav.innerHTML = Object.entries(rolePages[role]).map(([key, item]) => `<button class='nav-item ${key === 'dashboard' ? 'active' : ''}' data-page='${key}'><span class='nav-icon'>${item[0]}</span>${item[1]}</button>`).join('');
  if (store.students.length) render();
}

render = function roleAwareRender() {
  if (store.role === 'student') {
    document.querySelectorAll('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.page === store.page));
    document.getElementById('page-root').innerHTML = studentPortal();
    return;
  }
  if (store.role === 'lecturer' && store.page === 'grades') {
    document.querySelectorAll('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.page === store.page));
    document.getElementById('page-root').innerHTML = gradeManagement(true);
    bindGradePage(true);
    return;
  }
  if (store.role === 'admin' && store.page === 'grades') {
    document.querySelectorAll('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.page === store.page));
    document.getElementById('page-root').innerHTML = gradeManagement(false);
    bindGradePage(false);
    return;
  }
  if (store.role === 'admin' && store.page === 'dashboard') {
    document.querySelectorAll('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.page === store.page));
    document.getElementById('page-root').innerHTML = academicDashboard();
    bindPage();
    return;
  }
  if (store.role === 'lecturer' && (store.page === 'students' || store.page === 'courses')) {
    document.querySelectorAll('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.page === store.page));
    document.getElementById('page-root').innerHTML = lecturerManagement(store.page);
    return;
  }
  renderAdmin();
};

function demoStudent() { return store.students.find((student) => student.email.toLowerCase() === demoStudentEmail) || { id: '4', name: 'Alex Johnson', email: demoStudentEmail, major: 'Computer Science', enrolledCourses: [] }; }
function demoCourses() { const student = demoStudent(); return store.courses.filter((course) => student.enrolledCourses.some((enrolled) => enrolled.id === course.id)); }
function gradePoints(grade) { return ({ A:4, 'A-':3.7, 'B+':3.3, B:3, 'B-':2.7, 'C+':2.3, C:2, 'C-':1.7, D:1, F:0 })[grade] ?? 0; }
function gradeFor(course) { const item = store.grades.find((grade) => grade.student.email === demoStudentEmail && grade.course.id === course.id); return item ? [item.grade, gradePoints(item.grade)] : ['Pending', 0]; }
function studentGpa() { const courses = demoCourses().filter((course) => gradeFor(course)[0] !== 'Pending'); const total = courses.reduce((sum, course) => sum + course.credits * gradeFor(course)[1], 0); const credits = courses.reduce((sum, course) => sum + course.credits, 0); return credits ? (total / credits).toFixed(2) : '0.00'; }
function allGpas() { return store.students.map((student) => { const records = store.grades.filter((grade) => grade.student.id === student.id); const credits = records.reduce((sum, grade) => sum + grade.course.credits, 0); const points = records.reduce((sum, grade) => sum + grade.course.credits * gradePoints(grade.grade), 0); return { name: student.name, value: credits ? points / credits : 0 }; }).filter((item) => item.value); }
function academicDashboard() { const gpas = allGpas(); const average = gpas.length ? (gpas.reduce((sum, item) => sum + item.value, 0) / gpas.length).toFixed(2) : '0.00'; const highest = gpas.length ? Math.max(...gpas.map((item) => item.value)).toFixed(2) : '0.00'; const activity = store.grades.slice(-5).reverse(); return `<section class='page'><div class='page-head'><div><p class='eyebrow'>ACADEMIC ADMINISTRATION</p><h1>Campus overview</h1><p>Live academic performance and operational activity.</p></div><button class='button' data-modal='student'>+ Add student</button></div><div class='stats'>${stat('Total Students',store.students.length,'Active learners')}${stat('Total Courses',store.courses.length,'Course catalogue')}${stat('Grades Assigned',store.grades.length,'Academic records')}${stat('Average GPA',average,'Across graded students')}${stat('Highest GPA',highest,'Current leader')}${stat('Enrollments',store.enrollments.length,'Course placements')}</div><div class='dashboard-grid'><article class='card'><h2>Recent academic activity</h2><div class='feed'>${activity.map((item) => `<div class='feed-item'><span class='feed-dot'></span><div><p>Grade assigned: ${esc(item.grade)}</p><small>${esc(item.student.name)} · ${esc(item.course.title)}</small></div></div>`).join('') || '<p class=muted>No grades have been assigned.</p>'}</div></article><article class='card'><h2>Academic health</h2><p class=muted>${store.grades.length} grade records are linked to enrollment relationships.</p><div class='health'><b>GraphQL Connected</b><p>Grade validation active</p><p>GPA calculated from live data</p></div></article></div></section>`; }
function gradeManagement(lecturer) { const enrollmentOptions = store.enrollments.map((item) => `<option value='${item.student.id}:${item.course.id}'>${esc(item.student.name)} — ${esc(item.course.title)}</option>`).join(''); return `<section class='page'><div class='page-head'><div><p class='eyebrow'>${lecturer ? 'LECTURER WORKSPACE' : 'ACADEMIC ADMINISTRATION'}</p><h1>Grade Management</h1><p>Assign and update grades using enrolled student records.</p></div></div><div class='dashboard-grid'><article class='card'><h2>Assign grade</h2><form id='grade-form' class='modal-content'><label>Enrollment<select name='enrollment' required><option value=''>Select student and course</option>${enrollmentOptions}</select></label><label>Grade<select name='grade' required>${['A','A-','B+','B','B-','C+','C','C-','D','F'].map((grade) => `<option>${grade}</option>`).join('')}</select></label><button class='button'>Assign grade</button></form></article><article class='card'><h2>Grading rules</h2><p class='muted'>A student must be enrolled before a grade can be assigned. One grade record is allowed per student and course.</p></article></div><article class='card table-card' style='margin-top:18px'><div class='table-wrap'><table><thead><tr><th>Student</th><th>Course</th><th>Grade</th><th>Actions</th></tr></thead><tbody>${store.grades.map((item) => `<tr><td><b>${esc(item.student.name)}</b></td><td>${esc(item.course.title)}</td><td><select data-grade-select='${item.id}'>${['A','A-','B+','B','B-','C+','C','C-','D','F'].map((grade) => `<option ${grade===item.grade?'selected':''}>${grade}</option>`).join('')}</select></td><td class='actions'><button class='action' data-grade-save='${item.id}'>Update</button>${lecturer?'':`<button class='action delete' data-grade-delete='${item.id}'>Delete</button>`}</td></tr>`).join('') || '<tr><td colspan=4 class=empty>No grades assigned.</td></tr>'}</tbody></table></div></article></section>`; }
function bindGradePage(lecturer) { const root = document.getElementById('page-root'); const form = root.querySelector('#grade-form'); form.onsubmit = async (event) => { event.preventDefault(); const [studentId, courseId] = new FormData(form).get('enrollment').split(':'); try { await assignGrade({ studentId, courseId, grade: new FormData(form).get('grade') }); toast('Grade assigned.','success'); refreshData(true); } catch (error) { toast(error.message,'error'); } }; root.onclick = async (event) => { const save = event.target.closest('[data-grade-save]'); const remove = event.target.closest('[data-grade-delete]'); try { if (save) { await updateGrade(save.dataset.gradeSave,{ grade: root.querySelector(`[data-grade-select='${save.dataset.gradeSave}']`).value }); toast('Grade updated.','success'); refreshData(true); } if (remove && !lecturer) { await deleteGrade(remove.dataset.gradeDelete); toast('Grade deleted.','success'); refreshData(true); } } catch (error) { toast(error.message,'error'); } }; }
function lecturerManagement(type) { const rows = type === 'students' ? store.students.map((student) => `<tr><td><b>${esc(student.name)}</b></td><td>${esc(student.email)}</td><td>${esc(student.major)}</td><td>${pills(student.enrolledCourses)}</td></tr>`).join('') : store.courses.map((course) => `<tr><td><b>${esc(course.title)}</b></td><td>${course.credits}</td><td>${esc(course.instructor?.name || 'Unassigned')}</td><td>${course.enrolledStudents.length}</td></tr>`).join(''); const headers = type === 'students' ? '<th>Name</th><th>Email</th><th>Major</th><th>Enrolled Courses</th>' : '<th>Course</th><th>Credits</th><th>Instructor</th><th>Enrolled Students</th>'; return `<section class='page'><div class='page-head'><div><p class='eyebrow'>LECTURER WORKSPACE</p><h1>${type === 'students' ? 'Student Directory' : 'Assigned Courses'}</h1><p>View-only academic information for teaching staff.</p></div><div class='read-only'>No administrative actions available</div></div><article class='card table-card'><div class='table-wrap'><table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table></div></article></section>`; }
function studentPortal() {
  const student = demoStudent(); const courses = demoCourses();
  if (store.page === 'profile') return studentProfile(student);
  if (store.page === 'mycourses') return studentCourses(courses);
  if (store.page === 'grades') return studentGrades(courses);
  return `<section class='page'><div class='student-hero'><p class='eyebrow'>STUDENT SELF-SERVICE</p><h1>Welcome back, ${esc(student.name.split(' ')[0])}</h1><p>${esc(student.major)} · Student ID ${esc(student.id)}</p></div><div class='stats'>${stat('My Courses', courses.length, 'Current term')}${stat('Credits', courses.reduce((sum, course) => sum + course.credits, 0), 'In progress')}${stat('Current GPA', studentGpa(), 'Academic standing')}${stat('Profile', 'Active', 'Registration current')}</div><div class='dashboard-grid'><article class='card'><h2>My course schedule</h2><div class='feed'>${courses.map((course) => `<div class='feed-item'><span class='feed-dot'></span><div><p>${esc(course.title)}</p><small>${course.credits} credits · ${esc(course.instructor?.name || 'Instructor TBA')}</small></div></div>`).join('') || '<p class=muted>No courses assigned.</p>'}</div></article><article class='card'><h2>Academic summary</h2><p class='muted'>Your records are view-only in this demonstration portal.</p><div class='health'><b>Good standing</b><p>GraphQL student record connected</p><p>All current course enrollments shown</p></div></article></div></section>`;
}
function studentProfile(student) { return `<section class='page'><div class='page-head'><div><p class='eyebrow'>STUDENT SELF-SERVICE</p><h1>My Profile</h1><p>Personal academic information. This record is view-only.</p></div></div><article class='card'><div class='profile-card'><div><span>Full name</span><b>${esc(student.name)}</b></div><div><span>Student ID</span><b>${esc(student.id)}</b></div><div><span>Email</span><b>${esc(student.email)}</b></div><div><span>Major</span><b>${esc(student.major)}</b></div></div></article></section>`; }
function studentCourses(courses) { return `<section class='page'><div class='page-head'><div><p class='eyebrow'>STUDENT SELF-SERVICE</p><h1>My Courses</h1><p>Courses currently assigned to Alex Johnson.</p></div></div><article class='card table-card'><div class='table-wrap'><table><thead><tr><th>Course Name</th><th>Credits</th><th>Assigned Instructor</th></tr></thead><tbody>${courses.map((course) => `<tr><td><b>${esc(course.title)}</b></td><td>${course.credits}</td><td>${esc(course.instructor?.name || 'Instructor TBA')}</td></tr>`).join('') || '<tr><td colspan=3 class=empty>No courses assigned.</td></tr>'}</tbody></table></div></article></section>`; }
function studentGrades(courses) { return `<section class='page'><div class='page-head'><div><p class='eyebrow'>STUDENT SELF-SERVICE</p><h1>My Grades</h1><p>Academic performance for your current courses.</p></div><div class='read-only'>View-only academic record</div></div><div class='stats'>${stat('Current GPA', studentGpa(), 'Calculated from grades')}${stat('Completed Courses', courses.length, 'Current record')}</div><article class='card table-card'><div class='table-wrap'><table><thead><tr><th>Course</th><th>Grade</th><th>Grade points</th></tr></thead><tbody>${courses.map((course) => { const grade = gradeFor(course); return `<tr><td><b>${esc(course.title)}</b></td><td class='grade'>${grade[0]}</td><td>${grade[1].toFixed(1)}</td></tr>`; }).join('')}</tbody></table></div></article></section>`; }
function lecturerGrades() { return `<section class='page'><div class='page-head'><div><p class='eyebrow'>LECTURER WORKSPACE</p><h1>Grade overview</h1><p>Student performance preview for teaching staff.</p></div></div><article class='card table-card'><div class='table-wrap'><table><thead><tr><th>Student</th><th>Course</th><th>Grade</th></tr></thead><tbody>${store.enrollments.map((enrollment) => `<tr><td>${esc(enrollment.student.name)}</td><td>${esc(enrollment.course.title)}</td><td class='grade'>${enrollment.student.email === demoStudentEmail ? gradeFor(store.courses.find((course) => course.id === enrollment.course.id))[0] : 'Pending'}</td></tr>`).join('')}</tbody></table></div></article></section>`; }
const pages = { dashboard: ['▦','Dashboard'], students: ['◉','Students'], courses: ['▣','Courses'], instructors: ['♙','Instructors'], enrollments: ['↗','Enrollments'], settings: ['⚙','Settings'] };

document.addEventListener('DOMContentLoaded', () => { setupChrome(); refreshData(); });
async function request(query, variables = {}) {
  const operation = typeof query === 'string' ? query.trim() : '';
  if (!operation) throw new Error('Frontend prevented an empty GraphQL request. Check the browser console for the caller.');
  console.log('GraphQL Query:', operation, 'Variables:', variables);
  const response = await fetch(API, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query: operation, variables }) });
  const json = await response.json().catch(() => ({}));
  if (!response.ok || json.errors) throw Error(json.errors?.map((error) => error.message).join(' ') || 'Backend is unavailable.');
  return json.data;
}
async function fetchStudents(){store.students=(await request(`query{students{id name email major enrolledCourses{id title}}}`)).students;}
async function fetchCourses(){store.courses=(await request(`query{courses{id title credits instructorId instructor{id name} enrolledStudents{id name}}}`)).courses;}
async function fetchInstructors(){store.instructors=(await request(`query{instructors{id name department assignedCourses{id title}}}`)).instructors;}
async function fetchEnrollments(){store.enrollments=(await request(`query{enrollments{id student{id name} course{id title}}}`)).enrollments;}
async function createStudent(input){return request(`mutation($input:CreateStudentInput!){createStudent(input:$input){id}}`,{input});}
async function updateStudent(id,input){return request(`mutation($id:ID!,$input:UpdateStudentInput!){updateStudent(id:$id,input:$input){id}}`,{id,input});}
async function deleteStudent(id){return request(`mutation($id:ID!){deleteStudent(id:$id){id}}`,{id});}
async function createCourse(input){return request(`mutation($input:CreateCourseInput!){createCourse(input:$input){id}}`,{input});}
async function updateCourse(id,input){return request(`mutation($id:ID!,$input:UpdateCourseInput!){updateCourse(id:$id,input:$input){id}}`,{id,input});}
async function deleteCourse(id){return request(`mutation($id:ID!){deleteCourse(id:$id){id}}`,{id});}
async function createInstructor(input){return request(`mutation($input:CreateInstructorInput!){createInstructor(input:$input){id}}`,{input});}
async function updateInstructor(id,input){return request(`mutation($id:ID!,$input:UpdateInstructorInput!){updateInstructor(id:$id,input:$input){id}}`,{id,input});}
async function deleteInstructor(id){return request(`mutation($id:ID!){deleteInstructor(id:$id){id}}`,{id});}
async function enrollStudent(input){return request(`mutation($input:EnrollStudentInput!){enrollStudent(input:$input){id}}`,{input});}
async function deleteEnrollment(id){return request(`mutation($id:ID!){deleteEnrollment(id:$id){id}}`,{id});}

function setupChrome(){
 document.getElementById('navigation').innerHTML=Object.entries(pages).map(([key,[icon,name]])=>`<button class='nav-item ${key==='dashboard'?'active':''}' data-page='${key}'><span class='nav-icon'>${icon}</span>${name}</button>`).join('');
 document.getElementById('navigation').onclick=e=>{const b=e.target.closest('[data-page]');if(b){store.page=b.dataset.page;render();document.getElementById('sidebar').classList.remove('open');}};
 document.getElementById('refresh-button').onclick=()=>refreshData(false);
 document.getElementById('menu-button').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
 document.getElementById('theme-toggle').onclick=toggleTheme; document.getElementById('profile-settings').onclick=()=>{store.page='settings';render();};
 document.getElementById('global-search').oninput=e=>{store.filters.global=e.target.value.toLowerCase();if(store.page!=='dashboard')render();};
 if(localStorage.getItem('cc-theme')==='dark')document.body.classList.add('dark');
}
async function refreshData(initial=true){document.getElementById('page-root').innerHTML=skeleton();try{await Promise.all([fetchStudents(),fetchCourses(),fetchInstructors(),fetchEnrollments(),fetchGrades()]);render();if(!initial)toast('Data refreshed','success');}catch(e){toast(e.message,'error');document.getElementById('page-root').innerHTML=`<section class='page'><div class='card'><h2>Could not connect to CampusConnect</h2><p class='muted'>Start the GraphQL backend, then refresh this page.</p></div></section>`;}}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===store.page)); document.getElementById('page-root').innerHTML=store.page==='dashboard'?dashboard():store.page==='settings'?settings():management(store.page); bindPage();}
function dashboard(){const assignments=store.instructors.flatMap(i=>i.assignedCourses.map(c=>['Instructor assignment',`${i.name} teaches ${c.title}`]));const activities=[...store.students.slice(-2).reverse().map(s=>['New student added',s.name]),...store.enrollments.slice(-2).reverse().map(e=>['New enrollment',`${e.student.name} joined ${e.course.title}`]),...assignments.slice(-2)].slice(0,6);return `<section class='page'><div class='page-head'><div><p class='eyebrow'>ACADEMIC ADMINISTRATION</p><h1>Campus overview</h1><p>Live operational view of your university.</p></div><button class='button' data-modal='student'>+ Add student</button></div><div class='stats'>${stat('Total Students',store.students.length,'Active learners')}${stat('Total Courses',store.courses.length,'Course catalogue')}${stat('Total Instructors',store.instructors.length,'Teaching faculty')}${stat('Total Enrollments',store.enrollments.length,'Course placements')}</div><div class='dashboard-grid'><article class='card'><h2>Recent activity</h2><div class='feed'>${activities.length?activities.map(a=>`<div class='feed-item'><span class='feed-dot'></span><div><p>${esc(a[0])}</p><small>${esc(a[1])}</small></div></div>`).join(''):'<p class=muted>No recent activity.</p>'}</div></article><div><article class='card'><h2>Quick actions</h2><div class='quick-actions'><button data-modal='student'>◉ Add student</button><button data-modal='course'>▣ Add course</button><button data-modal='instructor'>♙ Add instructor</button><button data-modal='enrollment'>↗ Enroll student</button></div></article><article class='health'><b>System health</b><p>● GraphQL Connected</p><p>● Backend Online</p><p>● Docker ready</p></article></div></div></section>`;}
function management(type){const meta={students:['Students','Manage learner records and academic pathways.',['Name','Email','Major','Enrolled Courses']],courses:['Courses','Manage your course catalogue and teaching assignments.',['Course Title','Credits','Instructor','Enrollments']],instructors:['Instructors','Manage faculty and department assignments.',['Name','Department','Assigned Courses']],enrollments:['Enrollments','Manage student course registrations.',['Student','Course']]}[type];const items=filtered(type);const filter=type==='students'?selectFilter('major','Major',[...new Set(store.students.map(x=>x.major))]):type==='courses'?selectFilter('credits','Credits',[1,2,3,4,5,6]):type==='instructors'?selectFilter('department','Department',[...new Set(store.instructors.map(x=>x.department))]):'';return `<section class='page'><div class='page-head'><div><p class='eyebrow'>ADMINISTRATION</p><h1>${meta[0]}</h1><p>${meta[1]}</p></div><button class='button' data-modal='${type==='students'?'student':type==='courses'?'course':type==='instructors'?'instructor':'enrollment'}'>+ ${type==='enrollments'?'Enroll student':'Add '+type.slice(0,-1)}</button></div><div class='toolbar'><input id='table-search' placeholder='Search ${type}...' value='${esc(store.filters[type+'Search']||'')}'><span>${filter}</span></div><article class='card table-card'><div class='table-wrap'><table><thead><tr>${meta[2].map((h,i)=>`<th data-sort='${type}:${i}'>${h} ↕</th>`).join('')}<th>Actions</th></tr></thead><tbody>${items.length?items.map(x=>row(type,x)).join(''):`<tr><td class='empty' colspan='${meta[2].length+1}'>No ${type} found.</td></tr>`}</tbody></table></div></article></section>`;}
function row(type,x){if(type==='students')return `<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.email)}</td><td>${esc(x.major)}</td><td>${pills(x.enrolledCourses)}</td>${actions(type,x.id)}</tr>`;if(type==='courses')return `<tr><td><b>${esc(x.title)}</b></td><td>${x.credits}</td><td>${esc(x.instructor?.name||'Unassigned')}</td><td>${x.enrolledStudents.length}</td>${actions(type,x.id)}</tr>`;if(type==='instructors')return `<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.department)}</td><td>${pills(x.assignedCourses)}</td>${actions(type,x.id)}</tr>`;return `<tr><td><b>${esc(x.student.name)}</b></td><td>${esc(x.course.title)}</td>${actions(type,x.id,true)}</tr>`;}
function actions(type,id,remove=false){return `<td class='actions'><button class='action' data-view='${type}:${id}'>View</button>${!remove?`<button class='action' data-edit='${type}:${id}'>Edit</button>`:''}<button class='action delete' data-delete='${type}:${id}'>${remove?'Remove':'Delete'}</button></td>`;}
function filtered(type){let a=store[type];const q=(store.filters[type+'Search']||store.filters.global||'').toLowerCase();if(q)a=a.filter(x=>JSON.stringify(x).toLowerCase().includes(q));const f=store.filters[type+'Filter'];if(f){if(type==='students')a=a.filter(x=>x.major===f);if(type==='courses')a=a.filter(x=>String(x.credits)===f);if(type==='instructors')a=a.filter(x=>x.department===f);}const sort=store.sort[type];if(sort!==undefined)a=[...a].sort((a,b)=>String(value(type,a,sort)).localeCompare(String(value(type,b,sort)),undefined,{numeric:true}));return a;}
function value(type,x,i){return type==='students'?[x.name,x.email,x.major,x.enrolledCourses.length][i]:type==='courses'?[x.title,x.credits,x.instructor?.name,x.enrolledStudents.length][i]:type==='instructors'?[x.name,x.department,x.assignedCourses.length][i]:[x.student.name,x.course.title][i];}
function bindPage(){const root=document.getElementById('page-root');root.onclick=e=>{const m=e.target.closest('[data-modal]');if(m)return modal(m.dataset.modal);const edit=e.target.closest('[data-edit]');if(edit){const[t,id]=edit.dataset.edit.split(':');return modal(t.slice(0,-1),id);}const view=e.target.closest('[data-view]');if(view)return viewModal(...view.dataset.view.split(':'));const del=e.target.closest('[data-delete]');if(del)return confirmDelete(...del.dataset.delete.split(':'));const sort=e.target.closest('[data-sort]');if(sort){const[t,i]=sort.dataset.sort.split(':');store.sort[t]=+i;render();}if(e.target.id==='settings-theme')toggleTheme();};const search=root.querySelector('#table-search');if(search)search.oninput=e=>{store.filters[store.page+'Search']=e.target.value;render();};const filter=root.querySelector('#table-filter');if(filter)filter.onchange=e=>{store.filters[store.page+'Filter']=e.target.value;render();};}
function modal(type,id){const item=id&&store[type+'s']?.find(x=>x.id===id);const label=id?'Edit':'Add';const fields=type==='student'?[['name','Full name'],['email','Email address'],['major','Major']]:type==='course'?[['title','Course title'],['credits','Credits','number'],['instructorId','Assigned instructor','select']]:type==='instructor'?[['name','Full name'],['department','Department']]:[['studentId','Student','studentSelect'],['courseId','Course','courseSelect']];openModal(`${label} ${type}`,`<form id='entity-form'>${fields.map(f=>field(f,item)).join('')}<div class='modal-footer'><button class='button secondary' type='button' data-close>Cancel</button><button class='button'>${label} ${type}</button></div></form>`,async form=>{let input=Object.fromEntries(new FormData(form));if(type==='course')input.credits=Number(input.credits);if(!validate(type,input))return;const op=type==='student'?(id?updateStudent(id,input):createStudent(input)):type==='course'?(id?updateCourse(id,input):createCourse(input)):type==='instructor'?(id?updateInstructor(id,input):createInstructor(input)):enrollStudent(input);await op;closeModal();toast(`${type[0].toUpperCase()+type.slice(1)} saved.`,'success');refreshData(true);});}
function field(f,item){let val=item?.[f[0]]||'';if(f[2]==='select')return `<label>${f[1]}<select name='${f[0]}' required>${options(store.instructors,'name',val)}</select></label>`;if(f[2]==='studentSelect')return `<label>${f[1]}<select name='${f[0]}' required>${options(store.students,'name')}</select></label>`;if(f[2]==='courseSelect')return `<label>${f[1]}<select name='${f[0]}' required>${options(store.courses,'title')}</select></label>`;return `<label>${f[1]}<input name='${f[0]}' type='${f[2]||'text'}' value='${esc(val)}' ${f[0]==='credits'?'min=1 max=6':''} required></label>`;}
function options(items,key,selected=''){return `<option value=''>Select...</option>${items.map(x=>`<option value='${x.id}' ${x.id===selected?'selected':''}>${esc(x[key])}</option>`).join('')}`;}
function viewModal(type,id){const item=store[type]?.find(x=>x.id===id)||store[type+'s']?.find(x=>x.id===id);openModal(`${type.slice(0,-1)||type} details`,`<div class='modal-content'><pre>${esc(JSON.stringify(item,null,2))}</pre><div class='modal-footer'><button class='button' data-close>Close</button></div></div>`);}
function confirmDelete(type,id){openModal('Confirm action',`<div class='modal-content'><p>Are you sure? This action cannot be undone while relationship rules are enforced.</p><div class='modal-footer'><button class='button secondary' data-close>Cancel</button><button class='button danger' id='confirm-delete'>Delete</button></div></div>`);document.getElementById('confirm-delete').onclick=async()=>{try{await ({students:deleteStudent,courses:deleteCourse,instructors:deleteInstructor,enrollments:deleteEnrollment}[type])(id);closeModal();toast('Record deleted.','success');refreshData(true);}catch(e){toast(e.message,'error');}};}
function openModal(title,content,submit){document.getElementById('modal-root').innerHTML=`<div class='modal-backdrop'><div class='modal'><header><h2>${title}</h2><button class='icon-button' data-close>×</button></header>${content}</div></div>`;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);const form=document.getElementById('entity-form');if(form)form.onsubmit=async e=>{e.preventDefault();try{await submit(form);}catch(err){toast(err.message,'error');}};}
function closeModal(){document.getElementById('modal-root').innerHTML='';}function validate(type,input){if(type==='course'&&(input.credits<1||input.credits>6)){toast('Credits must be between 1 and 6.','warning');return false;}if(Object.values(input).some(x=>!String(x).trim())){toast('Please complete all required fields.','warning');return false;}return true;}
function selectFilter(key,label,items){return `<select id='table-filter'><option value=''>All ${label}s</option>${items.map(x=>`<option ${store.filters[store.page+'Filter']===String(x)?'selected':''}>${esc(x)}</option>`).join('')}</select>`;}function stat(label,count,sub){return `<article class='stat'><span>${label}</span><strong>${count}</strong><small>● ${sub}</small></article>`;}function pills(a=[]){return a.length?a.map(x=>`<span class='pill'>${esc(x.title||x.name)}</span>`).join(''):'<span class=pill>None</span>';}function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML;}function skeleton(){return `<section class='page'><div class='skeleton' style='width:170px'></div><div class='stats' style='margin-top:25px'>${[1,2,3,4].map(()=>'<div class=skeleton style=height:120px></div>').join('')}</div></section>`;}function toast(message,type){const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=message;document.getElementById('toast-region').append(t);setTimeout(()=>t.remove(),4500);}function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('cc-theme',document.body.classList.contains('dark')?'dark':'light');}function settings(){return `<section class='page'><div class='page-head'><div><p class=eyebrow>PLATFORM</p><h1>Settings</h1><p>Personalise your CampusConnect workspace.</p></div></div><article class='card'><h2>Appearance</h2><p class=muted>Theme preference is saved locally on this device.</p><button class='button secondary' id='settings-theme'>Toggle dark mode</button></article></section>`;}
